services:
  - type: web
    runtime: python
    name: ppat-bar-ai
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.fileWatcherType none --browser.gatherUsageStats false
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: GEMINI_API_KEY
        sync: false
